/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'p-4',
    'flex',
    'flex-col',
    'gap-4',
    'text-sm',
    'font-bold',
    'text-base',
    'block',
    'text-xs',
    'text-gray-500',
    'mb-1',
    'w-full',
    'border',
    'rounded',
    'px-2',
    'py-1',
    'text-gray-600',
    'text-orange-500',
    'bg-blue-600',
    'text-white',
    'py-2',
    'px-4',
    'disabled:opacity-40',
    'gap-1',
    'items-center',
    'gap-2',
    'text-red-500',
    'ml-1',
    'bg-red-50',
    'p-2',
    'flex-1',
    'border-blue-600',
    'text-blue-600',
    'py-1',
    'border-gray-300',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
